SOURCES = entity.c room.c runner.c
OBJECTS = entity.o room.o runner.o
HEADERS = entity.h room.h
CC = gcc
CFLAGS = 

Youtube: $(OBJECTS)
	$(CC) $(SOURCES) $(CFLAGS) -o BattleRoom
clean:
	rm -fR *o BattleRoom	
